### PR TITLE
Toggle Midi Action

### PR DESCRIPTION
**Pull request by Nauce**
Toggle Midi Action to play audio and midi no matter what mode is playing

### CODE REVIEW

**Comment by Nianna** [comment]
Hi,
can you explain what is the merit of introducing this toggle?
All possible playback options (selection, page, whole song etc.)  have 3 modes - audio, midi and audio with midi so if you want to use/stop using midi you can just use another shortcut for playback.

I'm not convinced about this change because currently with this new option enabled "Audio only" playback options will effectively become "audio & midi" which is misleading and introduces complexity.

Please explain your idea a bit.

**Comment by Nauce** [comment]
Hi Nianna,

Thank you for reply. I don't agree about the complexity with the play modes, because is your choice enable or disable that toggle. Without toggle midi option, you should always use CTRL shortcut keys, which can be so annoying when you always want to play with midi.

**Comment by Nianna** [comment]
From what I understood - what actually annoys you are the shortcuts which are not optimal for your way of using the app, right?

With customizable shortcuts you could just swap the shortcuts for all "Audio & midi" and "Audio only" playback options to have better UX. Maybe it is the answer?

I actually started implementing customizable shortcuts months ago and I believe I still have my changes on some branch...

Yeah, but it indroduces complexity in code/application logic as there are now more states to handle, we will have a new dimension - is "always midi" enabled? 
To have consistent application state, "Audio only" option should be disabled if "always midi" is enabled as it makes no sense, but this will block playback shortcuts without CTRL - no gain from this feature in regards to your needs.

Isn't what you really want a possibility to customize shortcuts since it is the shortcuts that annoy you :)?
Then you could just swap the shortcuts for all "Audio & midi" and "Audio only" playback options to have better UX.

**Comment by Nauce** [comment]
Yes, it's annoying when I'm editing a song and I always want to play "Audio & Midi" for a long time. I'd have to always use CTRL shortcut keys.

I'm not talking about shortcut's customization. I tought in an easy and fast way to enable temporarily "Audio & Midi" without using shortcut keys (turn "Audio only" to "Audio & Midi" or turn back).

It's true that it could be a new state or dimension. If you think that this is not the best option to accomplish it, we can close the pull request. I can have this option on my personal version to fits my needs.

**Comment by Nianna** [comment]
So you don't want to swap shortcuts to have more comfortable ones, but make e.g. the SPACE shortcut once play audio and once play audio & midi? Like it's currently with ticks? 

Then the only way that I see it (so that UI remains straightforward) we'd need to go all the way and turn midi into a feature like ticks - get rid of Audio & Midi, Audio only, Midi only modes from the menu and have "Toggle audio", "Toggle midi" and "Toggle ticks" options and just one shortcut per each playback option (selection, page, whole song etc.) - then the outcome would depend solely on toggles states.
Doable and maintainable, awesome configurability, straightforward effect, terrible UX for people who switch between A, M and A&M modes all the time, e.g. me :)

Let's do as you suggested, it's a great way to adjust the application for your needs in the fork where maintainability is not a big issue.

I mean, one additional toggle is still fine, but if we go this way more toggles will appear, cause it's the easiest way to customize something. I worked with a project were there were more than 200 toggles and it was hell - everything is so configurable that you have no idea how application works by looking at the code and writing new features is pure pain as you need to think how all toggle combinations can/should affect it.

I'll close this PR, but if you have any more improvements or ideas, feel free to contribute, I really liked your 2 other PRs and am very happy that you not only use the app, but also want to make it better.

**Pull request closed without merging**
